### ISSUE TITLE
インデントを正しくつけるようにしてください

### ISSUE THREAD

**Issue by yfujii01** [takayamazusa/janken#2]
@takayamazusa 
65,66行目のインデントがずれていると思います。
修正をお願いします。

**Comment by takayamazusa** [comment]
@yfujii01 
修正しました
6e832cc43dd7b949d268657c3b35df79e8b306ab

**Comment by yfujii01** [comment]
@takayamazusa 
まだずれているとことがありますね。
手動で直すのももちろんOKですが、visual studioであれば自動整形機能もあるので、そういったものを使うと簡単にきれいなコードにすることができます。

ここら辺が参考になるかと思います。
http://d.hatena.ne.jp/replication/20120329/1332947252
https://qiita.com/yohhoy/items/00993f05c14a79b70bdd
※visual studioのバージョンによって操作方法が異なることがあります。

**Comment by takayamazusa** [comment]
@yfujii01 
http://d.hatena.ne.jp/replication/20120329/1332947252
教えていただいた上記のサイトを参考に修正してみたのですが、
なぜか一番最初にあげた、不要なソースが混じっているものが
出てきてしまいました。

**Comment by yfujii01** [comment]
@takayamazusa 
謎ですね。
大量のコメントアウトされたファイルがフォーマットされているみたいです。

gitで管理する対象がよくわからないことになってますね。
設定を直す必要がありそうですが、ただの練習なので放置しましょうか。
