### ISSUE TITLE
コメントがもっとあったほうが良い

### ISSUE THREAD

**Issue by yfujii01** [takayamazusa/janken#3]
@takayamazusa 
フィールド変数やプロトタイプ宣言、条件分岐(if、switch)、繰り返し(for、while)の説明がそれぞれあると見やすくて良いコードになると思います。

**Comment by takayamazusa** [comment]
@yfujii01 
説明を追加しました
6e832cc43dd7b949d268657c3b35df79e8b306ab

**Comment by yfujii01** [comment]
@takayamazusa 
何のために作成したロジックなのか分かりやすくなって良いと思います。

コメントを入れる位置は以下の２パターンありますが
基本的に①を使うほうが多いです。(開発者によってまちまち)
横に長いコードより縦長のほうが好かれますので、今後意識してみると良いかと思います。
①ロジックの直前
```
(例)
//自分が出す手の数字をいれる変数
static int me;
```
②ロジックの後ろ
```
(例)
static int me; //自分が出す手の数字をいれる変数
```

※間違いではないのでじゃんけんはこのままでも良いです。
