### ISSUE TITLE
変数名などに意味を持たせる

### ISSUE THREAD

**Issue by yfujii01** [takayamazusa/janken#4]
@takayamazusa 
1文字だけの変数名(a,bなど)は後から見たときや、他人が見たときに何に使われているのか理解が難しいので何の値を持つ変数なのかを表す名前を付けたほうが良いです。

例えばaならユーザーのインプット文字列なのでuserInputとかplayerInputなど

**Comment by takayamazusa** [comment]
@yfujii01 
変数名を変更しました
6e832cc43dd7b949d268657c3b35df79e8b306ab

**Comment by yfujii01** [comment]
@takayamazusa 
:+1:
